version: "2"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    user: 'node'
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
     - ../:/home/node/app
    command: "sh ./scripts/entrypoints/${NPM_SCRIPT}.sh"
